language: csharp
mono: none
dist: xenial
dotnet: 3.1

install:
- dotnet restore

services:
- docker

script:
- dotnet build
- export VERSION_NUMBER=$(./ci_scripts/semver.sh)
- docker build -t disi33/personal_website:$VERSION_NUMBER .
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

after_success:
- docker push disi33/personal_website:$VERSION_NUMBER
- docker push disi33/personal_website:latest