language: csharp
mono: none
dist: xenial
dotnet: 3.1

install:
- dotnet restore

services:
- docker

script:
- dotnet build
- export VERSION_NUMBER=$(cat ./ci_scripts/semver.sh | bash)
- docker build -t disi33/personal_website:$VERSION_NUMBER .
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

after_success:
- docker push disi33/personal_website:$VERSION_NUMBER
- docker push disi33/personal_website:latest
- chmod +x ./ci_scripts/update_helm_chart.sh
- export HELM_CHART="website"
- git clone https://github.com/disi33/personal_website_helm_charts /tmp/helm_charts
- pushd /tmp/helm_charts/$HELM_CHART/
- echo $(pwd)
- echo $(ls)
- sed -i 's/[0-9]\+\.[0-9]\+\.[0-9]\+/$VERSION_NUMBER/g' /tmp/helm_charts/$HELM_CHART/values-imgtag.yaml
- sed -i 's/[0-9]\+\.[0-9]\+\.[0-9]\+/$VERSION_NUMBER/g' /tmp/helm_charts/$HELM_CHART/Chart.yaml
- git add /tmp/helm_charts/$HELM_CHART/values-imgtag.yaml
- git add /tmp/helm_charts/$HELM_CHART/Chart.yaml
- git commit -m "[auto] bump $HELM_CHART chart version number to $VERSION_NUMBER"
- git push origin master
- popd