version: 2.1

orbs:
  mem: circleci/rememborb@0.0.1
  dotnet: aetos382/dotnet@0.1.2

jobs:
  build-publish-update:
    machine: true
    steps:
      - checkout
      - mem/remember:
          env_var: VERSION_NUMBER
          value: '$(cat ./ci_scripts/semver.sh | bash)'
      - run: git config --global user.email "disi33@gmail.com"
      - run: git config --global user.name "CircleCI build agent"
      - run: wget -q https://packages.microsoft.com/config/ubuntu/19.10/packages-microsoft-prod.deb -O /tmp/packages-microsoft-prod.deb
      - run: sudo dpkg -i /tmp/packages-microsoft-prod.deb
      - run: sudo apt-get clean
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https tar dpkg
      - run: sudo apt-get update
      - run: sudo apt-get install dotnet-sdk-3.1 -y
      - dotnet/build:
          project: personal_website.csproj
          configuration: Release
      - run: docker build -t disi33/personal_website:$VERSION_NUMBER .
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push disi33/personal_website:$VERSION_NUMBER
      - run: docker tag disi33/personal_website:$VERSION_NUMBER disi33/personal_website:latest
      - run: docker push disi33/personal_website:latest
      - mem/recall:
          env_var: VERSION_NUMBER
      - run: chmod +x ./ci_scripts/update_helm_chart.sh
      - run: ./ci_scripts/update_helm_chart.sh $VERSION_NUMBER
workflows:
  version: 2
  my-workflow:
    jobs:
      - build-publish-update:
          context: personal_website
